name = "design-gallery-fastapi-worker"
main = "main.py"
compatibility_date = "2024-01-01"

# Database configuration
[[d1_databases]]
binding = "DB"
database_name = "design-gallery-db"
database_id = "d6b6a330-ee0e-4ffb-9382-51af55485da4"

# R2 bucket configuration for image storage
[[r2_buckets]]
binding = "GALLERY_BUCKET"
bucket_name = "design-gallery-images"

# Environment variables
[vars]
ENVIRONMENT = "development"
CLOUDFLARE_ACCOUNT_ID = "your-account-id"

# Production environment
[env.production]
name = "design-gallery-fastapi-worker"

[[env.production.d1_databases]]
binding = "DB"
database_name = "design-gallery-db"
database_id = "d6b6a330-ee0e-4ffb-9382-51af55485da4"

[[env.production.r2_buckets]]
binding = "GALLERY_BUCKET"
bucket_name = "design-gallery-images"

[env.production.vars]
ENVIRONMENT = "production"
CLOUDFLARE_ACCOUNT_ID = "your-account-id"

# Secrets (use wrangler secret put commands)
# JWT_SECRET - JWT signing secret
# CLOUDFLARE_API_TOKEN - Cloudflare API token (if needed for additional features) 